### PR TITLE
batch_insert should use python charset for encoding, not mysql (e.g. …

### PR DESCRIPTION
**Pull request by imreFitos**
…utf8 instead of utf8mb4)

Signed-off-by: imreFitos <imre.fitos@gmail.com>

### CODE REVIEW

**Comment by imreFitos** [comment]
Filed bug report linking to this pull request: http://bugs.mysql.com/80535

Already submitted the OCA contributor agreement.

**Comment by dveeden** [comment]
Note that latin1 in python is iso-8859-1(5) and latin1 in MySQL is cp1252, which is slightly different. So this commit might fix this also. Lgtm

**Comment by imreFitos** [comment]
My OCA paperwork has been submitted already.

**Comment by imreFitos** [comment]
Dear Oracle, as I have commented on February 28, I have submitted the OCA paperwork. It's your turn now to process it. Please re-open this issue.

**Comment by mysql-admin** [comment]
Hi,
We are looking into this - sorry for the confusion (re-opening)

Thanks
==Omer

**Comment by imreFitos** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Pull request closed without merging**
