### PR TITLE
Fix constraint introspection for table indices in Django

### PR DESCRIPTION
**Pull request by daneah**
### Dependencies

* `Django==2.0.7`
* `mysql-connector-python==8.0.11`

### Issue

When trying to run migrations to create the Django test database, Django introspects table constraints and expects to be able to know the type of each index on a given table. The Django MySQL backend adds this information [here](https://github.com/django/django/blob/master/django/db/backends/mysql/introspection.py#L204) and expects it to be available [here](https://github.com/django/django/blob/master/django/db/backends/base/schema.py#L1044). The `mysql-connector-python` backend does not seem to add this information and ultimately produces a `KeyError` when trying to look up `'type'` during introspection. The change contained here addresses this by doing precisely what Django's built-in MySQL backend does.

### CODE REVIEW

**Comment by daneah** [comment]
I've submitted the OCA. I don't have a MySQL bug system account, but I used an email from my GitHub account. Please let me know if that does not suffice.

**Comment by mysql-admin** [comment]
Hi daneah,

Thanks for submitting this contribution. 
We do need you to have a user in http://bugs.mysql.com so we can continue tracking this contribution and make sure we attribute it to you.. Please register at https://dev.mysql.com/auth/register/

Thanks
==Omer

**Comment by daneah** [comment]
Thanks Omer, it turns out I did already have an Oracle account, so I updated the email of that account to match the email I used in the OCA. Please let me know if you need anything else!

**Comment by daneah** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Comment by daneah** [comment]
Is there an expected release cycle for this bugfix?

**Pull request closed without merging**
